// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tencentBidding.proto

package tencent

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	Id                   *string               `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	At                   *uint32               `protobuf:"varint,2,opt,name=at" json:"at,omitempty"`
	Site                 *Request_Site         `protobuf:"bytes,3,opt,name=site" json:"site,omitempty"`
	Device               *Request_Device       `protobuf:"bytes,4,opt,name=device" json:"device,omitempty"`
	User                 *Request_User         `protobuf:"bytes,5,opt,name=user" json:"user,omitempty"`
	Impression           []*Request_Impression `protobuf:"bytes,6,rep,name=impression" json:"impression,omitempty"`
	DEPRECATEDInnerInfo  *string               `protobuf:"bytes,7,opt,name=DEPRECATED_inner_info,json=DEPRECATEDInnerInfo" json:"DEPRECATED_inner_info,omitempty"`
	App                  *Request_App          `protobuf:"bytes,8,opt,name=app" json:"app,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a648fe17faba17c, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *Request) GetAt() uint32 {
	if m != nil && m.At != nil {
		return *m.At
	}
	return 0
}

func (m *Request) GetSite() *Request_Site {
	if m != nil {
		return m.Site
	}
	return nil
}

func (m *Request) GetDevice() *Request_Device {
	if m != nil {
		return m.Device
	}
	return nil
}

func (m *Request) GetUser() *Request_User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *Request) GetImpression() []*Request_Impression {
	if m != nil {
		return m.Impression
	}
	return nil
}

func (m *Request) GetDEPRECATEDInnerInfo() string {
	if m != nil && m.DEPRECATEDInnerInfo != nil {
		return *m.DEPRECATEDInnerInfo
	}
	return ""
}

func (m *Request) GetApp() *Request_App {
	if m != nil {
		return m.App
	}
	return nil
}

type Request_Impression struct {
	Id                   *string                              `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Tagid                *string                              `protobuf:"bytes,2,opt,name=tagid" json:"tagid,omitempty"`
	Bidfloor             *float32                             `protobuf:"fixed32,3,opt,name=bidfloor" json:"bidfloor,omitempty"`
	Banner               *Request_Impression_Banner           `protobuf:"bytes,4,opt,name=banner" json:"banner,omitempty"`
	Video                *Request_Impression_Video            `protobuf:"bytes,5,opt,name=video" json:"video,omitempty"`
	Clientid             *string                              `protobuf:"bytes,6,opt,name=clientid" json:"clientid,omitempty"`
	Tradecode            *string                              `protobuf:"bytes,7,opt,name=tradecode" json:"tradecode,omitempty"`
	SnsLists             *string                              `protobuf:"bytes,8,opt,name=sns_lists,json=snsLists" json:"sns_lists,omitempty"`
	Dealid               *string                              `protobuf:"bytes,9,opt,name=dealid" json:"dealid,omitempty"`
	AdmRequire           []*Request_Impression_MaterialFormat `protobuf:"bytes,10,rep,name=adm_require,json=admRequire" json:"adm_require,omitempty"`
	ImpExt               *Request_Impression_ImpExt           `protobuf:"bytes,11,opt,name=imp_ext,json=impExt" json:"imp_ext,omitempty"`
	Channel              *string                              `protobuf:"bytes,12,opt,name=channel" json:"channel,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                             `json:"-"`
	XXX_unrecognized     []byte                               `json:"-"`
	XXX_sizecache        int32                                `json:"-"`
}

func (m *Request_Impression) Reset()         { *m = Request_Impression{} }
func (m *Request_Impression) String() string { return proto.CompactTextString(m) }
func (*Request_Impression) ProtoMessage()    {}
func (*Request_Impression) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a648fe17faba17c, []int{0, 0}
}

func (m *Request_Impression) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request_Impression.Unmarshal(m, b)
}
func (m *Request_Impression) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request_Impression.Marshal(b, m, deterministic)
}
func (m *Request_Impression) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request_Impression.Merge(m, src)
}
func (m *Request_Impression) XXX_Size() int {
	return xxx_messageInfo_Request_Impression.Size(m)
}
func (m *Request_Impression) XXX_DiscardUnknown() {
	xxx_messageInfo_Request_Impression.DiscardUnknown(m)
}

var xxx_messageInfo_Request_Impression proto.InternalMessageInfo

func (m *Request_Impression) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *Request_Impression) GetTagid() string {
	if m != nil && m.Tagid != nil {
		return *m.Tagid
	}
	return ""
}

func (m *Request_Impression) GetBidfloor() float32 {
	if m != nil && m.Bidfloor != nil {
		return *m.Bidfloor
	}
	return 0
}

func (m *Request_Impression) GetBanner() *Request_Impression_Banner {
	if m != nil {
		return m.Banner
	}
	return nil
}

func (m *Request_Impression) GetVideo() *Request_Impression_Video {
	if m != nil {
		return m.Video
	}
	return nil
}

func (m *Request_Impression) GetClientid() string {
	if m != nil && m.Clientid != nil {
		return *m.Clientid
	}
	return ""
}

func (m *Request_Impression) GetTradecode() string {
	if m != nil && m.Tradecode != nil {
		return *m.Tradecode
	}
	return ""
}

func (m *Request_Impression) GetSnsLists() string {
	if m != nil && m.SnsLists != nil {
		return *m.SnsLists
	}
	return ""
}

func (m *Request_Impression) GetDealid() string {
	if m != nil && m.Dealid != nil {
		return *m.Dealid
	}
	return ""
}

func (m *Request_Impression) GetAdmRequire() []*Request_Impression_MaterialFormat {
	if m != nil {
		return m.AdmRequire
	}
	return nil
}

func (m *Request_Impression) GetImpExt() *Request_Impression_ImpExt {
	if m != nil {
		return m.ImpExt
	}
	return nil
}

func (m *Request_Impression) GetChannel() string {
	if m != nil && m.Channel != nil {
		return *m.Channel
	}
	return ""
}

type Request_Impression_ImpExt struct {
	Chid                 *uint32  `protobuf:"varint,1,opt,name=chid" json:"chid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request_Impression_ImpExt) Reset()         { *m = Request_Impression_ImpExt{} }
func (m *Request_Impression_ImpExt) String() string { return proto.CompactTextString(m) }
func (*Request_Impression_ImpExt) ProtoMessage()    {}
func (*Request_Impression_ImpExt) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a648fe17faba17c, []int{0, 0, 0}
}

func (m *Request_Impression_ImpExt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request_Impression_ImpExt.Unmarshal(m, b)
}
func (m *Request_Impression_ImpExt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request_Impression_ImpExt.Marshal(b, m, deterministic)
}
func (m *Request_Impression_ImpExt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request_Impression_ImpExt.Merge(m, src)
}
func (m *Request_Impression_ImpExt) XXX_Size() int {
	return xxx_messageInfo_Request_Impression_ImpExt.Size(m)
}
func (m *Request_Impression_ImpExt) XXX_DiscardUnknown() {
	xxx_messageInfo_Request_Impression_ImpExt.DiscardUnknown(m)
}

var xxx_messageInfo_Request_Impression_ImpExt proto.InternalMessageInfo

func (m *Request_Impression_ImpExt) GetChid() uint32 {
	if m != nil && m.Chid != nil {
		return *m.Chid
	}
	return 0
}

type Request_Impression_Banner struct {
	Width                *uint32  `protobuf:"varint,1,opt,name=width" json:"width,omitempty"`
	Height               *uint32  `protobuf:"varint,2,opt,name=height" json:"height,omitempty"`
	Mimes                []string `protobuf:"bytes,3,rep,name=mimes" json:"mimes,omitempty"`
	ExtraStyle           *string  `protobuf:"bytes,4,opt,name=extra_style,json=extraStyle" json:"extra_style,omitempty"`
	Visibility           *uint32  `protobuf:"varint,5,opt,name=visibility" json:"visibility,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request_Impression_Banner) Reset()         { *m = Request_Impression_Banner{} }
func (m *Request_Impression_Banner) String() string { return proto.CompactTextString(m) }
func (*Request_Impression_Banner) ProtoMessage()    {}
func (*Request_Impression_Banner) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a648fe17faba17c, []int{0, 0, 1}
}

func (m *Request_Impression_Banner) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request_Impression_Banner.Unmarshal(m, b)
}
func (m *Request_Impression_Banner) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request_Impression_Banner.Marshal(b, m, deterministic)
}
func (m *Request_Impression_Banner) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request_Impression_Banner.Merge(m, src)
}
func (m *Request_Impression_Banner) XXX_Size() int {
	return xxx_messageInfo_Request_Impression_Banner.Size(m)
}
func (m *Request_Impression_Banner) XXX_DiscardUnknown() {
	xxx_messageInfo_Request_Impression_Banner.DiscardUnknown(m)
}

var xxx_messageInfo_Request_Impression_Banner proto.InternalMessageInfo

func (m *Request_Impression_Banner) GetWidth() uint32 {
	if m != nil && m.Width != nil {
		return *m.Width
	}
	return 0
}

func (m *Request_Impression_Banner) GetHeight() uint32 {
	if m != nil && m.Height != nil {
		return *m.Height
	}
	return 0
}

func (m *Request_Impression_Banner) GetMimes() []string {
	if m != nil {
		return m.Mimes
	}
	return nil
}

func (m *Request_Impression_Banner) GetExtraStyle() string {
	if m != nil && m.ExtraStyle != nil {
		return *m.ExtraStyle
	}
	return ""
}

func (m *Request_Impression_Banner) GetVisibility() uint32 {
	if m != nil && m.Visibility != nil {
		return *m.Visibility
	}
	return 0
}

type Request_Impression_Video struct {
	Mimes                []string `protobuf:"bytes,1,rep,name=mimes" json:"mimes,omitempty"`
	Linearity            *uint32  `protobuf:"varint,2,opt,name=linearity" json:"linearity,omitempty"`
	Minduration          *uint32  `protobuf:"varint,3,opt,name=minduration" json:"minduration,omitempty"`
	Maxduration          *uint32  `protobuf:"varint,4,opt,name=maxduration" json:"maxduration,omitempty"`
	Protocol             *uint32  `protobuf:"varint,5,opt,name=protocol" json:"protocol,omitempty"`
	Width                *uint32  `protobuf:"varint,6,opt,name=width" json:"width,omitempty"`
	Height               *uint32  `protobuf:"varint,7,opt,name=height" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request_Impression_Video) Reset()         { *m = Request_Impression_Video{} }
func (m *Request_Impression_Video) String() string { return proto.CompactTextString(m) }
func (*Request_Impression_Video) ProtoMessage()    {}
func (*Request_Impression_Video) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a648fe17faba17c, []int{0, 0, 2}
}

func (m *Request_Impression_Video) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request_Impression_Video.Unmarshal(m, b)
}
func (m *Request_Impression_Video) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request_Impression_Video.Marshal(b, m, deterministic)
}
func (m *Request_Impression_Video) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request_Impression_Video.Merge(m, src)
}
func (m *Request_Impression_Video) XXX_Size() int {
	return xxx_messageInfo_Request_Impression_Video.Size(m)
}
func (m *Request_Impression_Video) XXX_DiscardUnknown() {
	xxx_messageInfo_Request_Impression_Video.DiscardUnknown(m)
}

var xxx_messageInfo_Request_Impression_Video proto.InternalMessageInfo

func (m *Request_Impression_Video) GetMimes() []string {
	if m != nil {
		return m.Mimes
	}
	return nil
}

func (m *Request_Impression_Video) GetLinearity() uint32 {
	if m != nil && m.Linearity != nil {
		return *m.Linearity
	}
	return 0
}

func (m *Request_Impression_Video) GetMinduration() uint32 {
	if m != nil && m.Minduration != nil {
		return *m.Minduration
	}
	return 0
}

func (m *Request_Impression_Video) GetMaxduration() uint32 {
	if m != nil && m.Maxduration != nil {
		return *m.Maxduration
	}
	return 0
}

func (m *Request_Impression_Video) GetProtocol() uint32 {
	if m != nil && m.Protocol != nil {
		return *m.Protocol
	}
	return 0
}

func (m *Request_Impression_Video) GetWidth() uint32 {
	if m != nil && m.Width != nil {
		return *m.Width
	}
	return 0
}

func (m *Request_Impression_Video) GetHeight() uint32 {
	if m != nil && m.Height != nil {
		return *m.Height
	}
	return 0
}

type Request_Impression_MaterialFormat struct {
	Width                *uint32  `protobuf:"varint,1,opt,name=width" json:"width,omitempty"`
	Height               *uint32  `protobuf:"varint,2,opt,name=height" json:"height,omitempty"`
	Mimes                *string  `protobuf:"bytes,3,opt,name=mimes" json:"mimes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request_Impression_MaterialFormat) Reset()         { *m = Request_Impression_MaterialFormat{} }
func (m *Request_Impression_MaterialFormat) String() string { return proto.CompactTextString(m) }
func (*Request_Impression_MaterialFormat) ProtoMessage()    {}
func (*Request_Impression_MaterialFormat) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a648fe17faba17c, []int{0, 0, 3}
}

func (m *Request_Impression_MaterialFormat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request_Impression_MaterialFormat.Unmarshal(m, b)
}
func (m *Request_Impression_MaterialFormat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request_Impression_MaterialFormat.Marshal(b, m, deterministic)
}
func (m *Request_Impression_MaterialFormat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request_Impression_MaterialFormat.Merge(m, src)
}
func (m *Request_Impression_MaterialFormat) XXX_Size() int {
	return xxx_messageInfo_Request_Impression_MaterialFormat.Size(m)
}
func (m *Request_Impression_MaterialFormat) XXX_DiscardUnknown() {
	xxx_messageInfo_Request_Impression_MaterialFormat.DiscardUnknown(m)
}

var xxx_messageInfo_Request_Impression_MaterialFormat proto.InternalMessageInfo

func (m *Request_Impression_MaterialFormat) GetWidth() uint32 {
	if m != nil && m.Width != nil {
		return *m.Width
	}
	return 0
}

func (m *Request_Impression_MaterialFormat) GetHeight() uint32 {
	if m != nil && m.Height != nil {
		return *m.Height
	}
	return 0
}

func (m *Request_Impression_MaterialFormat) GetMimes() string {
	if m != nil && m.Mimes != nil {
		return *m.Mimes
	}
	return ""
}

type Request_Site struct {
	Name                 *string  `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Page                 *string  `protobuf:"bytes,2,opt,name=page" json:"page,omitempty"`
	Ref                  *string  `protobuf:"bytes,3,opt,name=ref" json:"ref,omitempty"`
	Channel              *string  `protobuf:"bytes,4,opt,name=channel" json:"channel,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request_Site) Reset()         { *m = Request_Site{} }
func (m *Request_Site) String() string { return proto.CompactTextString(m) }
func (*Request_Site) ProtoMessage()    {}
func (*Request_Site) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a648fe17faba17c, []int{0, 1}
}

func (m *Request_Site) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request_Site.Unmarshal(m, b)
}
func (m *Request_Site) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request_Site.Marshal(b, m, deterministic)
}
func (m *Request_Site) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request_Site.Merge(m, src)
}
func (m *Request_Site) XXX_Size() int {
	return xxx_messageInfo_Request_Site.Size(m)
}
func (m *Request_Site) XXX_DiscardUnknown() {
	xxx_messageInfo_Request_Site.DiscardUnknown(m)
}

var xxx_messageInfo_Request_Site proto.InternalMessageInfo

func (m *Request_Site) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Request_Site) GetPage() string {
	if m != nil && m.Page != nil {
		return *m.Page
	}
	return ""
}

func (m *Request_Site) GetRef() string {
	if m != nil && m.Ref != nil {
		return *m.Ref
	}
	return ""
}

func (m *Request_Site) GetChannel() string {
	if m != nil && m.Channel != nil {
		return *m.Channel
	}
	return ""
}

type Request_Device struct {
	Ip                   *string             `protobuf:"bytes,1,opt,name=ip" json:"ip,omitempty"`
	Ua                   *string             `protobuf:"bytes,2,opt,name=ua" json:"ua,omitempty"`
	Geo                  *Request_Device_Geo `protobuf:"bytes,3,opt,name=geo" json:"geo,omitempty"`
	Idfa                 *string             `protobuf:"bytes,4,opt,name=idfa" json:"idfa,omitempty"`
	IdfaEnc              *uint32             `protobuf:"varint,5,opt,name=idfa_enc,json=idfaEnc" json:"idfa_enc,omitempty"`
	Openudid             *string             `protobuf:"bytes,6,opt,name=openudid" json:"openudid,omitempty"`
	Carrier              *uint32             `protobuf:"varint,7,opt,name=carrier" json:"carrier,omitempty"`
	Make                 *string             `protobuf:"bytes,8,opt,name=make" json:"make,omitempty"`
	Model                *string             `protobuf:"bytes,9,opt,name=model" json:"model,omitempty"`
	Os                   *string             `protobuf:"bytes,10,opt,name=os" json:"os,omitempty"`
	Osv                  *string             `protobuf:"bytes,11,opt,name=Osv" json:"Osv,omitempty"`
	Js                   *uint32             `protobuf:"varint,12,opt,name=Js" json:"Js,omitempty"`
	Connectiontype       *uint32             `protobuf:"varint,13,opt,name=connectiontype" json:"connectiontype,omitempty"`
	Devicetype           *uint32             `protobuf:"varint,14,opt,name=devicetype" json:"devicetype,omitempty"`
	Mac                  *string             `protobuf:"bytes,15,opt,name=mac" json:"mac,omitempty"`
	Imei                 *string             `protobuf:"bytes,16,opt,name=imei" json:"imei,omitempty"`
	Androidid            *string             `protobuf:"bytes,17,opt,name=androidid" json:"androidid,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Request_Device) Reset()         { *m = Request_Device{} }
func (m *Request_Device) String() string { return proto.CompactTextString(m) }
func (*Request_Device) ProtoMessage()    {}
func (*Request_Device) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a648fe17faba17c, []int{0, 2}
}

func (m *Request_Device) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request_Device.Unmarshal(m, b)
}
func (m *Request_Device) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request_Device.Marshal(b, m, deterministic)
}
func (m *Request_Device) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request_Device.Merge(m, src)
}
func (m *Request_Device) XXX_Size() int {
	return xxx_messageInfo_Request_Device.Size(m)
}
func (m *Request_Device) XXX_DiscardUnknown() {
	xxx_messageInfo_Request_Device.DiscardUnknown(m)
}

var xxx_messageInfo_Request_Device proto.InternalMessageInfo

func (m *Request_Device) GetIp() string {
	if m != nil && m.Ip != nil {
		return *m.Ip
	}
	return ""
}

func (m *Request_Device) GetUa() string {
	if m != nil && m.Ua != nil {
		return *m.Ua
	}
	return ""
}

func (m *Request_Device) GetGeo() *Request_Device_Geo {
	if m != nil {
		return m.Geo
	}
	return nil
}

func (m *Request_Device) GetIdfa() string {
	if m != nil && m.Idfa != nil {
		return *m.Idfa
	}
	return ""
}

func (m *Request_Device) GetIdfaEnc() uint32 {
	if m != nil && m.IdfaEnc != nil {
		return *m.IdfaEnc
	}
	return 0
}

func (m *Request_Device) GetOpenudid() string {
	if m != nil && m.Openudid != nil {
		return *m.Openudid
	}
	return ""
}

func (m *Request_Device) GetCarrier() uint32 {
	if m != nil && m.Carrier != nil {
		return *m.Carrier
	}
	return 0
}

func (m *Request_Device) GetMake() string {
	if m != nil && m.Make != nil {
		return *m.Make
	}
	return ""
}

func (m *Request_Device) GetModel() string {
	if m != nil && m.Model != nil {
		return *m.Model
	}
	return ""
}

func (m *Request_Device) GetOs() string {
	if m != nil && m.Os != nil {
		return *m.Os
	}
	return ""
}

func (m *Request_Device) GetOsv() string {
	if m != nil && m.Osv != nil {
		return *m.Osv
	}
	return ""
}

func (m *Request_Device) GetJs() uint32 {
	if m != nil && m.Js != nil {
		return *m.Js
	}
	return 0
}

func (m *Request_Device) GetConnectiontype() uint32 {
	if m != nil && m.Connectiontype != nil {
		return *m.Connectiontype
	}
	return 0
}

func (m *Request_Device) GetDevicetype() uint32 {
	if m != nil && m.Devicetype != nil {
		return *m.Devicetype
	}
	return 0
}

func (m *Request_Device) GetMac() string {
	if m != nil && m.Mac != nil {
		return *m.Mac
	}
	return ""
}

func (m *Request_Device) GetImei() string {
	if m != nil && m.Imei != nil {
		return *m.Imei
	}
	return ""
}

func (m *Request_Device) GetAndroidid() string {
	if m != nil && m.Androidid != nil {
		return *m.Androidid
	}
	return ""
}

type Request_Device_Geo struct {
	Latitude             *float32 `protobuf:"fixed32,1,opt,name=latitude" json:"latitude,omitempty"`
	Longitude            *float32 `protobuf:"fixed32,2,opt,name=longitude" json:"longitude,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request_Device_Geo) Reset()         { *m = Request_Device_Geo{} }
func (m *Request_Device_Geo) String() string { return proto.CompactTextString(m) }
func (*Request_Device_Geo) ProtoMessage()    {}
func (*Request_Device_Geo) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a648fe17faba17c, []int{0, 2, 0}
}

func (m *Request_Device_Geo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request_Device_Geo.Unmarshal(m, b)
}
func (m *Request_Device_Geo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request_Device_Geo.Marshal(b, m, deterministic)
}
func (m *Request_Device_Geo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request_Device_Geo.Merge(m, src)
}
func (m *Request_Device_Geo) XXX_Size() int {
	return xxx_messageInfo_Request_Device_Geo.Size(m)
}
func (m *Request_Device_Geo) XXX_DiscardUnknown() {
	xxx_messageInfo_Request_Device_Geo.DiscardUnknown(m)
}

var xxx_messageInfo_Request_Device_Geo proto.InternalMessageInfo

func (m *Request_Device_Geo) GetLatitude() float32 {
	if m != nil && m.Latitude != nil {
		return *m.Latitude
	}
	return 0
}

func (m *Request_Device_Geo) GetLongitude() float32 {
	if m != nil && m.Longitude != nil {
		return *m.Longitude
	}
	return 0
}

type Request_User struct {
	Id                   *string  `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Buyerid              *string  `protobuf:"bytes,2,opt,name=buyerid" json:"buyerid,omitempty"`
	Gender               *string  `protobuf:"bytes,3,opt,name=gender" json:"gender,omitempty"`
	Age                  *uint32  `protobuf:"varint,4,opt,name=age" json:"age,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request_User) Reset()         { *m = Request_User{} }
func (m *Request_User) String() string { return proto.CompactTextString(m) }
func (*Request_User) ProtoMessage()    {}
func (*Request_User) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a648fe17faba17c, []int{0, 3}
}

func (m *Request_User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request_User.Unmarshal(m, b)
}
func (m *Request_User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request_User.Marshal(b, m, deterministic)
}
func (m *Request_User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request_User.Merge(m, src)
}
func (m *Request_User) XXX_Size() int {
	return xxx_messageInfo_Request_User.Size(m)
}
func (m *Request_User) XXX_DiscardUnknown() {
	xxx_messageInfo_Request_User.DiscardUnknown(m)
}

var xxx_messageInfo_Request_User proto.InternalMessageInfo

func (m *Request_User) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *Request_User) GetBuyerid() string {
	if m != nil && m.Buyerid != nil {
		return *m.Buyerid
	}
	return ""
}

func (m *Request_User) GetGender() string {
	if m != nil && m.Gender != nil {
		return *m.Gender
	}
	return ""
}

func (m *Request_User) GetAge() uint32 {
	if m != nil && m.Age != nil {
		return *m.Age
	}
	return 0
}

type Request_App struct {
	Id                   *string  `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name                 *string  `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Domain               *string  `protobuf:"bytes,3,opt,name=domain" json:"domain,omitempty"`
	Cat                  []string `protobuf:"bytes,4,rep,name=cat" json:"cat,omitempty"`
	Sectioncat           []string `protobuf:"bytes,5,rep,name=sectioncat" json:"sectioncat,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request_App) Reset()         { *m = Request_App{} }
func (m *Request_App) String() string { return proto.CompactTextString(m) }
func (*Request_App) ProtoMessage()    {}
func (*Request_App) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a648fe17faba17c, []int{0, 4}
}

func (m *Request_App) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request_App.Unmarshal(m, b)
}
func (m *Request_App) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request_App.Marshal(b, m, deterministic)
}
func (m *Request_App) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request_App.Merge(m, src)
}
func (m *Request_App) XXX_Size() int {
	return xxx_messageInfo_Request_App.Size(m)
}
func (m *Request_App) XXX_DiscardUnknown() {
	xxx_messageInfo_Request_App.DiscardUnknown(m)
}

var xxx_messageInfo_Request_App proto.InternalMessageInfo

func (m *Request_App) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *Request_App) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Request_App) GetDomain() string {
	if m != nil && m.Domain != nil {
		return *m.Domain
	}
	return ""
}

func (m *Request_App) GetCat() []string {
	if m != nil {
		return m.Cat
	}
	return nil
}

func (m *Request_App) GetSectioncat() []string {
	if m != nil {
		return m.Sectioncat
	}
	return nil
}

type Response struct {
	Id                   *string             `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Bidid                *string             `protobuf:"bytes,2,opt,name=bidid" json:"bidid,omitempty"`
	Seatbid              []*Response_SeatBid `protobuf:"bytes,3,rep,name=seatbid" json:"seatbid,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a648fe17faba17c, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *Response) GetBidid() string {
	if m != nil && m.Bidid != nil {
		return *m.Bidid
	}
	return ""
}

func (m *Response) GetSeatbid() []*Response_SeatBid {
	if m != nil {
		return m.Seatbid
	}
	return nil
}

type Response_Bid struct {
	Id                   *string  `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Impid                *string  `protobuf:"bytes,2,opt,name=impid" json:"impid,omitempty"`
	Price                *float32 `protobuf:"fixed32,3,opt,name=price" json:"price,omitempty"`
	Adid                 *string  `protobuf:"bytes,4,opt,name=adid" json:"adid,omitempty"`
	Nurl                 *string  `protobuf:"bytes,5,opt,name=nurl" json:"nurl,omitempty"`
	Adm                  *string  `protobuf:"bytes,6,opt,name=adm" json:"adm,omitempty"`
	Ext                  *string  `protobuf:"bytes,7,opt,name=ext" json:"ext,omitempty"`
	AdmPara              *string  `protobuf:"bytes,8,opt,name=adm_para,json=admPara" json:"adm_para,omitempty"`
	DeprecatedRespinfo   *string  `protobuf:"bytes,9,opt,name=deprecated_respinfo,json=deprecatedRespinfo" json:"deprecated_respinfo,omitempty"`
	Ext2                 *string  `protobuf:"bytes,10,opt,name=ext2" json:"ext2,omitempty"`
	DispExts             []string `protobuf:"bytes,11,rep,name=disp_exts,json=dispExts" json:"disp_exts,omitempty"`
	ClickExts            []string `protobuf:"bytes,12,rep,name=click_exts,json=clickExts" json:"click_exts,omitempty"`
	Ext3                 *string  `protobuf:"bytes,13,opt,name=ext3" json:"ext3,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response_Bid) Reset()         { *m = Response_Bid{} }
func (m *Response_Bid) String() string { return proto.CompactTextString(m) }
func (*Response_Bid) ProtoMessage()    {}
func (*Response_Bid) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a648fe17faba17c, []int{1, 0}
}

func (m *Response_Bid) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response_Bid.Unmarshal(m, b)
}
func (m *Response_Bid) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response_Bid.Marshal(b, m, deterministic)
}
func (m *Response_Bid) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response_Bid.Merge(m, src)
}
func (m *Response_Bid) XXX_Size() int {
	return xxx_messageInfo_Response_Bid.Size(m)
}
func (m *Response_Bid) XXX_DiscardUnknown() {
	xxx_messageInfo_Response_Bid.DiscardUnknown(m)
}

var xxx_messageInfo_Response_Bid proto.InternalMessageInfo

func (m *Response_Bid) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *Response_Bid) GetImpid() string {
	if m != nil && m.Impid != nil {
		return *m.Impid
	}
	return ""
}

func (m *Response_Bid) GetPrice() float32 {
	if m != nil && m.Price != nil {
		return *m.Price
	}
	return 0
}

func (m *Response_Bid) GetAdid() string {
	if m != nil && m.Adid != nil {
		return *m.Adid
	}
	return ""
}

func (m *Response_Bid) GetNurl() string {
	if m != nil && m.Nurl != nil {
		return *m.Nurl
	}
	return ""
}

func (m *Response_Bid) GetAdm() string {
	if m != nil && m.Adm != nil {
		return *m.Adm
	}
	return ""
}

func (m *Response_Bid) GetExt() string {
	if m != nil && m.Ext != nil {
		return *m.Ext
	}
	return ""
}

func (m *Response_Bid) GetAdmPara() string {
	if m != nil && m.AdmPara != nil {
		return *m.AdmPara
	}
	return ""
}

func (m *Response_Bid) GetDeprecatedRespinfo() string {
	if m != nil && m.DeprecatedRespinfo != nil {
		return *m.DeprecatedRespinfo
	}
	return ""
}

func (m *Response_Bid) GetExt2() string {
	if m != nil && m.Ext2 != nil {
		return *m.Ext2
	}
	return ""
}

func (m *Response_Bid) GetDispExts() []string {
	if m != nil {
		return m.DispExts
	}
	return nil
}

func (m *Response_Bid) GetClickExts() []string {
	if m != nil {
		return m.ClickExts
	}
	return nil
}

func (m *Response_Bid) GetExt3() string {
	if m != nil && m.Ext3 != nil {
		return *m.Ext3
	}
	return ""
}

type Response_SeatBid struct {
	Bid                  []*Response_Bid `protobuf:"bytes,1,rep,name=bid" json:"bid,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Response_SeatBid) Reset()         { *m = Response_SeatBid{} }
func (m *Response_SeatBid) String() string { return proto.CompactTextString(m) }
func (*Response_SeatBid) ProtoMessage()    {}
func (*Response_SeatBid) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a648fe17faba17c, []int{1, 1}
}

func (m *Response_SeatBid) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response_SeatBid.Unmarshal(m, b)
}
func (m *Response_SeatBid) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response_SeatBid.Marshal(b, m, deterministic)
}
func (m *Response_SeatBid) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response_SeatBid.Merge(m, src)
}
func (m *Response_SeatBid) XXX_Size() int {
	return xxx_messageInfo_Response_SeatBid.Size(m)
}
func (m *Response_SeatBid) XXX_DiscardUnknown() {
	xxx_messageInfo_Response_SeatBid.DiscardUnknown(m)
}

var xxx_messageInfo_Response_SeatBid proto.InternalMessageInfo

func (m *Response_SeatBid) GetBid() []*Response_Bid {
	if m != nil {
		return m.Bid
	}
	return nil
}

func init() {
	proto.RegisterType((*Request)(nil), "Request")
	proto.RegisterType((*Request_Impression)(nil), "Request.Impression")
	proto.RegisterType((*Request_Impression_ImpExt)(nil), "Request.Impression.ImpExt")
	proto.RegisterType((*Request_Impression_Banner)(nil), "Request.Impression.Banner")
	proto.RegisterType((*Request_Impression_Video)(nil), "Request.Impression.Video")
	proto.RegisterType((*Request_Impression_MaterialFormat)(nil), "Request.Impression.MaterialFormat")
	proto.RegisterType((*Request_Site)(nil), "Request.Site")
	proto.RegisterType((*Request_Device)(nil), "Request.Device")
	proto.RegisterType((*Request_Device_Geo)(nil), "Request.Device.Geo")
	proto.RegisterType((*Request_User)(nil), "Request.User")
	proto.RegisterType((*Request_App)(nil), "Request.App")
	proto.RegisterType((*Response)(nil), "Response")
	proto.RegisterType((*Response_Bid)(nil), "Response.Bid")
	proto.RegisterType((*Response_SeatBid)(nil), "Response.SeatBid")
}

func init() { proto.RegisterFile("tencentBidding.proto", fileDescriptor_4a648fe17faba17c) }

var fileDescriptor_4a648fe17faba17c = []byte{
	// 1172 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x56, 0xc1, 0x6e, 0x1b, 0x37,
	0x13, 0x86, 0xb4, 0xb2, 0x64, 0x8d, 0x62, 0x27, 0xa1, 0xf3, 0xff, 0xd8, 0xa8, 0x69, 0xe2, 0x06,
	0x68, 0x6a, 0xb4, 0x80, 0x02, 0xd8, 0x97, 0xde, 0x8a, 0x38, 0x71, 0x03, 0x07, 0x2d, 0x1a, 0x30,
	0x69, 0x0f, 0xbd, 0x08, 0xd4, 0x72, 0x2c, 0x13, 0xd9, 0xe5, 0x6e, 0x48, 0xca, 0xb5, 0x5f, 0xa0,
	0xb7, 0x3e, 0x4f, 0x4f, 0x7d, 0x80, 0x3c, 0x44, 0xdf, 0xa5, 0x98, 0x21, 0xb5, 0xab, 0x38, 0xee,
	0xa5, 0x27, 0xcd, 0x37, 0xdf, 0x68, 0x48, 0x7e, 0x9c, 0x19, 0x2e, 0xdc, 0x0b, 0x68, 0x0b, 0xb4,
	0xe1, 0xd8, 0x68, 0x6d, 0xec, 0x72, 0xd6, 0xb8, 0x3a, 0xd4, 0x8f, 0xff, 0xbc, 0x0d, 0x23, 0x89,
	0xef, 0x57, 0xe8, 0x83, 0xd8, 0x85, 0xbe, 0xd1, 0x79, 0x6f, 0xbf, 0x77, 0x30, 0x96, 0x7d, 0xa3,
	0x09, 0xab, 0x90, 0xf7, 0xf7, 0x7b, 0x07, 0x3b, 0xb2, 0xaf, 0x82, 0xf8, 0x02, 0x06, 0xde, 0x04,
	0xcc, 0xb3, 0xfd, 0xde, 0xc1, 0xe4, 0x70, 0x67, 0x96, 0xfe, 0x37, 0x7b, 0x63, 0x02, 0x4a, 0xa6,
	0xc4, 0x57, 0x30, 0xd4, 0x78, 0x61, 0x0a, 0xcc, 0x07, 0x1c, 0x74, 0xbb, 0x0d, 0x7a, 0xc1, 0x6e,
	0x99, 0x68, 0xca, 0xb5, 0xf2, 0xe8, 0xf2, 0xad, 0x6b, 0xb9, 0x7e, 0xf6, 0xe8, 0x24, 0x53, 0xe2,
	0x08, 0xc0, 0x54, 0x8d, 0x43, 0xef, 0x4d, 0x6d, 0xf3, 0xe1, 0x7e, 0x76, 0x30, 0x39, 0xdc, 0x6b,
	0x03, 0x4f, 0x5b, 0x4a, 0x6e, 0x84, 0x89, 0x43, 0xf8, 0xdf, 0x8b, 0x93, 0xd7, 0xf2, 0xe4, 0xf9,
	0xb3, 0xb7, 0x27, 0x2f, 0xe6, 0xc6, 0x5a, 0x74, 0x73, 0x63, 0xcf, 0xea, 0x7c, 0xc4, 0xc7, 0xda,
	0xeb, 0xc8, 0x53, 0xe2, 0x4e, 0xed, 0x59, 0x2d, 0x1e, 0x42, 0xa6, 0x9a, 0x26, 0xdf, 0xe6, 0xad,
	0xdc, 0x6a, 0x57, 0x78, 0xd6, 0x34, 0x92, 0x88, 0xe9, 0xef, 0x23, 0x80, 0x6e, 0xb9, 0x4f, 0x64,
	0xba, 0x07, 0x5b, 0x41, 0x2d, 0x8d, 0x66, 0xa5, 0xc6, 0x32, 0x02, 0x31, 0x85, 0xed, 0x85, 0xd1,
	0x67, 0x65, 0x5d, 0x3b, 0x16, 0xac, 0x2f, 0x5b, 0x2c, 0x0e, 0x61, 0xb8, 0x50, 0xb4, 0x7c, 0x52,
	0x69, 0x7a, 0xc3, 0xa9, 0x66, 0xc7, 0x1c, 0x21, 0x53, 0xa4, 0x78, 0x0a, 0x5b, 0x17, 0x46, 0x63,
	0x9d, 0x14, 0xbb, 0x7f, 0xd3, 0x5f, 0x7e, 0xa1, 0x00, 0x19, 0xe3, 0x68, 0x03, 0x45, 0x69, 0xd0,
	0x06, 0xa3, 0xf3, 0x21, 0xef, 0xac, 0xc5, 0xe2, 0x01, 0x8c, 0x83, 0x53, 0x1a, 0x8b, 0x5a, 0x63,
	0x52, 0xa6, 0x73, 0x88, 0xcf, 0x60, 0xec, 0xad, 0x9f, 0x97, 0xc6, 0x07, 0xcf, 0xaa, 0x8c, 0xe5,
	0xb6, 0xb7, 0xfe, 0x07, 0xc2, 0xe2, 0xff, 0x74, 0xc3, 0xaa, 0x34, 0x3a, 0x1f, 0x33, 0x93, 0x90,
	0x78, 0x0e, 0x13, 0xa5, 0xab, 0xb9, 0xc3, 0xf7, 0x2b, 0xe3, 0x30, 0x07, 0xbe, 0xae, 0xc7, 0x37,
	0xed, 0xf2, 0x47, 0x15, 0xd0, 0x19, 0x55, 0x7e, 0x5f, 0xbb, 0x4a, 0x05, 0x09, 0x4a, 0x57, 0x32,
	0xfe, 0x4b, 0x1c, 0xc1, 0xc8, 0x54, 0xcd, 0x1c, 0x2f, 0x43, 0x3e, 0xf9, 0x77, 0x65, 0x4e, 0xab,
	0xe6, 0xe4, 0x32, 0xc8, 0xa1, 0xe1, 0x5f, 0x91, 0xc3, 0xa8, 0x38, 0x27, 0x91, 0xca, 0xfc, 0x16,
	0x6f, 0x69, 0x0d, 0xa7, 0x0f, 0x60, 0x18, 0x63, 0x85, 0x80, 0x41, 0x71, 0x9e, 0x6e, 0x6d, 0x47,
	0xb2, 0x3d, 0xfd, 0xa3, 0x07, 0xc3, 0x28, 0x32, 0x5d, 0xe1, 0x6f, 0x46, 0x87, 0xf3, 0xc4, 0x47,
	0x40, 0x47, 0x3d, 0x47, 0xb3, 0x3c, 0x5f, 0xf7, 0x40, 0x42, 0x14, 0x5d, 0x99, 0x0a, 0x7d, 0x9e,
	0xed, 0x67, 0x74, 0xe1, 0x0c, 0xc4, 0x23, 0x98, 0xe0, 0x65, 0x70, 0x6a, 0xee, 0xc3, 0x55, 0x19,
	0xeb, 0x7f, 0x2c, 0x81, 0x5d, 0x6f, 0xc8, 0x23, 0x1e, 0x02, 0x5c, 0x18, 0x6f, 0x16, 0xa6, 0x34,
	0xe1, 0x8a, 0xaf, 0x71, 0x47, 0x6e, 0x78, 0xa6, 0x1f, 0x7a, 0xb0, 0xc5, 0x37, 0xd8, 0x2d, 0xd0,
	0xdb, 0x5c, 0xe0, 0x01, 0x8c, 0x4b, 0x63, 0x51, 0x39, 0xfa, 0x7b, 0xdc, 0x51, 0xe7, 0x10, 0xfb,
	0x30, 0xa9, 0x8c, 0xd5, 0x2b, 0xa7, 0x02, 0xb5, 0x4b, 0xc6, 0xfc, 0xa6, 0x8b, 0x23, 0xd4, 0x65,
	0x1b, 0x31, 0x48, 0x11, 0x9d, 0x8b, 0x4a, 0x86, 0xa7, 0x42, 0x51, 0x97, 0x69, 0x7f, 0x2d, 0xee,
	0x24, 0x1a, 0xde, 0x2c, 0xd1, 0x68, 0x53, 0xa2, 0xe9, 0x5b, 0xd8, 0xfd, 0xf8, 0x9a, 0xff, 0xbb,
	0xc4, 0xbd, 0x56, 0x81, 0xe9, 0xaf, 0x30, 0xa0, 0x59, 0x43, 0xb7, 0x69, 0x55, 0x85, 0xa9, 0x07,
	0xd9, 0x26, 0x5f, 0xa3, 0x96, 0x98, 0x9a, 0x90, 0x6d, 0x71, 0x07, 0x32, 0x87, 0x67, 0x29, 0x07,
	0x99, 0x9b, 0xb5, 0x32, 0xf8, 0xb8, 0x56, 0xfe, 0xce, 0x60, 0x18, 0x67, 0x14, 0x37, 0x78, 0xd3,
	0x36, 0x78, 0x43, 0x78, 0xa5, 0x52, 0xe2, 0xfe, 0x4a, 0x89, 0x2f, 0x21, 0x5b, 0x62, 0x9d, 0xc6,
	0xe0, 0xde, 0xb5, 0x09, 0x37, 0x7b, 0x89, 0xb5, 0x24, 0x9e, 0x76, 0x64, 0xf4, 0x99, 0x4a, 0x0b,
	0xb1, 0x2d, 0xee, 0xc3, 0x36, 0xfd, 0xce, 0xd1, 0x16, 0x49, 0xe1, 0x11, 0xe1, 0x13, 0x5b, 0x90,
	0xf8, 0x75, 0x83, 0x76, 0xa5, 0xbb, 0x7e, 0x5d, 0x63, 0xde, 0xb6, 0x72, 0xce, 0xa0, 0x4b, 0x3a,
	0xaf, 0x21, 0x2d, 0x52, 0xa9, 0x77, 0x98, 0xda, 0x94, 0x6d, 0x16, 0xaf, 0xd6, 0x58, 0xa6, 0x0e,
	0x8d, 0x80, 0x4e, 0x51, 0xfb, 0x1c, 0xe2, 0x29, 0x6a, 0x4f, 0xe2, 0xfc, 0xe4, 0x2f, 0xb8, 0xcf,
	0xc6, 0x92, 0x4c, 0x8a, 0x78, 0xe5, 0xb9, 0x87, 0x76, 0x64, 0xff, 0x95, 0x17, 0x4f, 0x60, 0xb7,
	0xa8, 0xad, 0xc5, 0x82, 0x8a, 0x23, 0x5c, 0x35, 0x98, 0xef, 0x30, 0x77, 0xcd, 0x4b, 0x85, 0x1d,
	0xa7, 0x3a, 0xc7, 0xec, 0xc6, 0xc2, 0xee, 0x3c, 0xb4, 0x52, 0xa5, 0x8a, 0xfc, 0x76, 0x5c, 0xa9,
	0x52, 0x05, 0x4b, 0x53, 0xa1, 0xc9, 0xef, 0x24, 0x69, 0x2a, 0x34, 0x54, 0xde, 0xca, 0x6a, 0x57,
	0x1b, 0x12, 0xe0, 0x6e, 0x9c, 0x49, 0xad, 0x63, 0xfa, 0x1d, 0x64, 0x2f, 0xe3, 0x50, 0x2b, 0x55,
	0x30, 0x61, 0xa5, 0xe3, 0xed, 0xf7, 0x65, 0x8b, 0xb9, 0x3f, 0x6a, 0xbb, 0x8c, 0x64, 0x9f, 0xc9,
	0xce, 0x41, 0xb5, 0x43, 0x6f, 0xcb, 0x27, 0xd3, 0x3b, 0x87, 0xd1, 0x62, 0x75, 0x85, 0xae, 0x9d,
	0xdf, 0x6b, 0x48, 0xb5, 0xb9, 0x44, 0xab, 0xd1, 0xa5, 0x02, 0x4a, 0x88, 0x8e, 0x43, 0x85, 0x16,
	0xfb, 0x87, 0xcc, 0xa9, 0x87, 0xec, 0x59, 0xd3, 0x7c, 0x92, 0x7a, 0x5d, 0xa6, 0xfd, 0x8d, 0x32,
	0xa5, 0xf1, 0x59, 0x57, 0xca, 0xd8, 0x75, 0xd2, 0x88, 0x28, 0x69, 0xa1, 0x42, 0x3e, 0xe0, 0x86,
	0x27, 0x93, 0x54, 0xf5, 0x51, 0x64, 0x22, 0xb6, 0x98, 0xd8, 0xf0, 0x3c, 0xfe, 0x90, 0xc1, 0xb6,
	0x44, 0xdf, 0xd4, 0xd6, 0xe3, 0x4d, 0x6f, 0xd2, 0x82, 0x85, 0x4c, 0x6f, 0x12, 0x03, 0xf1, 0x0d,
	0x8c, 0x3c, 0xaa, 0xb0, 0x30, 0x9a, 0x47, 0xd7, 0xe4, 0xf0, 0xee, 0x6c, 0x9d, 0x61, 0xf6, 0x06,
	0x15, 0x7d, 0x1a, 0xc8, 0x75, 0xc4, 0xf4, 0xaf, 0x3e, 0x64, 0xc7, 0xf1, 0x2b, 0xe0, 0x7a, 0x6a,
	0x53, 0x35, 0x5d, 0x6a, 0x06, 0xe4, 0x6d, 0x1c, 0xbd, 0xfb, 0xf1, 0xad, 0x8b, 0x80, 0x14, 0x50,
	0xb4, 0x8b, 0xd4, 0x02, 0x64, 0xb3, 0x2a, 0x2b, 0x17, 0x07, 0x0c, 0xa9, 0xb2, 0x72, 0x25, 0x4b,
	0xaa, 0xab, 0x54, 0xf6, 0x64, 0x92, 0x87, 0x5e, 0x81, 0xf8, 0x36, 0x91, 0x49, 0xad, 0x43, 0x0f,
	0x4c, 0xa3, 0x9c, 0x4a, 0xd5, 0x3e, 0x52, 0xba, 0x7a, 0xad, 0x9c, 0x12, 0x4f, 0x61, 0x4f, 0x63,
	0xe3, 0xb0, 0x50, 0x01, 0xf5, 0xdc, 0xa1, 0x6f, 0xf8, 0xc9, 0x8f, 0xe5, 0x2f, 0x3a, 0x4a, 0x26,
	0x86, 0xf6, 0x80, 0x97, 0xe1, 0x30, 0x75, 0x03, 0xdb, 0xf4, 0xea, 0x69, 0xe3, 0xf9, 0xf1, 0xf1,
	0xf9, 0x84, 0xe5, 0xde, 0x26, 0xc7, 0xc9, 0x65, 0xf0, 0xe2, 0x73, 0x80, 0xa2, 0x34, 0xc5, 0xbb,
	0xc8, 0xde, 0x62, 0x76, 0xcc, 0x1e, 0xa6, 0x63, 0xbe, 0x23, 0xee, 0x8f, 0x98, 0xef, 0x68, 0xfa,
	0x35, 0x8c, 0x92, 0xa6, 0xe2, 0x11, 0x64, 0x0b, 0xd6, 0x30, 0x4b, 0xdf, 0x3a, 0x49, 0x73, 0xd2,
	0x9b, 0x98, 0xe3, 0x6f, 0xe1, 0x49, 0x51, 0x57, 0x33, 0xa5, 0xdf, 0x99, 0x30, 0xd3, 0x58, 0x29,
	0xab, 0xbd, 0xd1, 0xd8, 0x94, 0x2a, 0x9c, 0xd5, 0xae, 0x9a, 0x71, 0x07, 0xcf, 0x5c, 0x58, 0x1c,
	0xef, 0xbe, 0xfd, 0xe8, 0x2b, 0xee, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x89, 0x17, 0x40, 0x36,
	0xd6, 0x09, 0x00, 0x00,
}
